config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  root to: 'static#homepage'
end

app/models/admin_user.rb
class AdminUser < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :date, :rationale, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]

  def index
    @posts = Post.all.includes(:user)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to @post, notice: "Your post was created successfully"
    else
      render :new
    end
  end

  def show

  end

  private

    def post_params
      params.require(:post).permit(:date, :rationale)
    end

    def set_post
      @post = Post.find(params[:id])
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def homepage
    #code
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def active?(path)
    "active" if current_page?(path)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OvertimeManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    	<div class="row">
    		<div class="col-md-12">
    			<%= render 'shared/navigation' %>
    			<%= yield %>
    		</div>
    	</div>
  </div>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>
				#
			</th>
			<th>
				Date
			</th>
			<th>
				User
			</th>
			<th>
				Rationale
			</th>
		</tr>
	</thead>
	<tbody>
		<% @posts.each do |post| %>
			<tr>
				<td>
					<%= post.id %>
				</td>
				<td>
					<%= post.date %>
				</td>
				<td>
					<%= post.user.last_name %>
				</td>
				<td>
					<%= truncate(post.rationale) %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
  <%= f.date_field :date %>
  <%= f.text_area :rationale %>

  <%= f.submit 'Save', class: 'btn btn-default' %>
<%end%>

app/views/posts/show.html.erb
<%= @post.inspect%>

app/views/shared/_navigation.html.erb
<div class='logo'>
	<h1>Time Tracker</h1>
</div>

<ul class="custom-nav nav nav-tabs">
	<li class="<%= active?(root_path)%>">
		<%= link_to "Home", root_path %>
	</li>
	<li class="<%= active?(posts_path)%>">
		<%= link_to "Time Entries", posts_path %>
	</li>
	<li class="dropdown pull-right">
		 <a href="#" data-toggle="dropdown" class="dropdown-toggle">Account<strong class="caret"></strong></a>
		<ul class="dropdown-menu">
			<li>
				<%= link_to "Edit Details", edit_user_registration_path %>
			</li>
			<li class="divider">
			</li>
			<li>
				<%= link_to "Logout", destroy_user_session_path, method: :delete %>
			</li>
		</ul>
	</li>
</ul>